-- Survey 1 Data Query
-- Purpose: Extract survey 1 responses
-- 
-- Required columns (MUST be included):
--   YRMO (date in YYMM format), LTR (satisfaction score),
--   ResponseID, Timestamp
--
-- Expected additional columns:
--   Custom_Metric_1, Custom_Metric_2, Custom_Metric_3, 
--   Custom_Metric_4, Custom_Metric_5,
--   [any additional survey-specific columns]
--
-- Add your SQL query below: